name: Expiration Cron Jobs

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes (UTC)

jobs:
  attendance_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      # âœ… Create .env file from GitHub Secrets
      - name: Create env file
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env

      - name: Run Expiration Script
        run: |
          echo "===== Expiration Script Started ====="
          node src/jobs/index.js
          echo "===== Expiration Script Finished ====="
